#! /usr/bin/env python3
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
# File name: ***_system.py
# First Edit: 2020-06-30
# Last Change: 30-Jun-2020.
"""
This content is property of SomebodysDream.
Author: Zac Shepherd (SomebodysDream)
"""
# Generic system set up, need to update the system factory: include and the map
# also need to update the logger manager and game manager

# *** System
from .base_system import System

from common.managers.event_manager import Event

class ***System(System):
    def __init__(self, game_state, entity_manager, event_manager, logger):
        super().__init__(game_state, entity_manager, event_manager, logger)
        
        self.logger = logger.loggers[***_system']

    def post_event(self, event_type, data):
        self.event_manager.post(Event(event_type, data))

    def get_component(self, entity, component):
        return self.entity_manager.get_component(entity, component)

    def has_component(self, entity, component):
        return self.entity_manager.has_component(entity, component)
    

    def update(self, delta_time):
        pass